### ISSUE TITLE
In FileUploadWidget.ts, matchesMimeType is not triggered on click of chooseFileButton. Potential security risk?

### ISSUE THREAD

**Issue by codematsing** [jrief/django-formset#251]
# Expected Behavior
* Given:
  * UploadedFileInput(attrs={'accept': 'image/jpeg, image/png'}) [or some other mimeType
  * File uploaded is pdf [or some other mimeType that conflicts with accept]
* Then:
  * If user clicks on `Choose File`OR drops file with incorrect filetype: Widget should not accept file

# Actual Behavior
* If user clicks on `Choose File`: Widget still accepts file

# Findings
* matchesMimeType is present on fileDrop function
* should matchesMimeType instead be a condition inside [`FileUploadWidget.uploadFiles`](https://github.com/jrief/django-formset/blob/releases/1.5/client/django-formset/FileUploadWidget.ts#L122)?

# Extra Information
* Using windows OS. In Windows File Explorer, there is a feature to still show all files which can force to choose files with unaccepted file types
* During validation on form submit, will still reject the incorrect filetype; however,
* For security reasons, the file can still be potentially uploaded in UPLOAD_TEMP_DIR, thus still be injected into the server (at least from my understanding of the file upload process)
* Using django-formset==2.2

# Supporting Proof

In video the following actions were taken:
* Upload correct filetype via drag and drop: successfully accepted file
* Upload **wrong** filetype via drag and drop: successfully declined file
* Upload correct filetype via choosing file: successfully accepted file
* Upload **wrong** filteype via choosing file: failed to decline file, instead accepted
![Image](https://github.com/user-attachments/assets/8604e0fd-b85a-4cd9-b791-d71a1293888a)

Magnification of Explorer Window:
<img width="1322" height="762" alt="Image" src="https://github.com/user-attachments/assets/eff8048e-4167-4ed3-8bf6-18e352db0241" />

**Comment by jrief** [comment]
Sorry, it will take some time until I can check this.

**Comment by codematsing** [comment]
No worries, I just noticed this. It's not breaking issue, and backend validation will still catch this as an error (thus, will not push through and save on DB). But it might also be something to be wary of for potential file injection on temp folder.

I've also started experimenting on a fix for this but since I'm new to the typescript environment, I'm taking my time to upskill along the way. If I'm able to try and provide a suggested approach on this I'll push a PR for your review or refactoring.

**Comment by BuntlineAtSea** [comment]
If there's a security problem here, it's not that the *client* doesn't check the mime type, it's that the *server* seemingly doesn't either (on the temp file).

I don't know whether files with unexpected mime types being saved in UPLOAD_TEMP_DIR is a security risk, but if it is, the solution is obviously *not* to politely ask the client to run some code for us and to please refrain from uploading nasty files - and then to continue blindly accepting whatever it does upload. If files with arbitrary mime types in UPLOAD_TEMP_DIR are a security problem, it's the server that needs to refuse them. 

Without knowing much about the django-formset javascript, it sounds like this is indeed something that should be fixed on the client. But that can only ever be a cosmetic / UX fix, not a security one.

**Comment by jrief** [comment]
I just tested again on branch `releases/2.2`. The MIME-type is now checked on the client when uploading. It additionally is checked after submission by the server-side code.
@codematsing Please recheck in your environment and if everything works fine, I will release it in version 2.2.3.

**Comment by codematsing** [comment]
Hi! Sorry for the late response — I was on holiday.

I tested this again and reviewed the referenced [code commit](https://github.com/jrief/django-formset/commit/38205521bf075fcfa8c489cf1666a1a1c41c8c19).
Unfortunately, the issue is still present.

I think there may have been a miscommunication or misunderstanding of my original concern. The problem is **not** related to the drag-and-drop upload, but specifically to the **`chooseFileButton.onClick`** flow.

**Current behavior:**
✅ When a file is dragged and dropped, the widget behaves correctly and rejects invalid file types.
❌ When a file is selected via the file chooser, and an invalid file type is deliberately chosen, the widget still accepts the file.

From what I can tell, `FileUploadWidget.matchesMimeType` is invoked during `FileUploadWidget.handleFileDrop`, but it is not called when files are selected via the chooseFileButton.onClick handler. This is why the current behavior is observed.

It seems to me that `FileUploadWidget.matchesMimeType` should instead (or additionally) be invoked inside `FileUploadWidget.uploadFiles`, since both drag-and-drop and file selection ultimately pass through this code path. That would ensure consistent validation regardless of how the file is added.

____________________________

That said, I agree with @BuntlineAtSea that this is only a client-side validation mechanism and that files must still be revalidated on the backend before being cached in UPLOAD_TEMP_DIR.

For this reason, in my own project I also override the backend receiver [FileUploadMixin.receive_uploaded_file](https://github.com/jrief/django-formset/blob/releases/2.2/formset/upload.py#L90) to evaluate invalid MIME types before proceeding with returning a valid `JsonResponse` dict. Something like code below. I can only show a pseudo-code since my project is under django-formset<2.x release, but the idea is generally the same.

```python
# overriding formset.upload.FileUploadMixin
class FileUploadMixin:
  def receive_uploaded_file(file_obj, image_height=None):
    if not file_obj:
        raise UploadFileException("File upload failed")
    
    # content type validation
    valid_content_type: list = #some code to get valid content types
    if file_obj.content_type not in valid_content_types:
       raise UploadFileException("Invalid file type")

    # continue code as is...
    # NOTE: doing content type validation (see above snippet)
    # before continuing code ensures file_obj will not be saved in UPLOAD_TEMP_DIR
    # for invalid or unaccepted content_type or mimetypes

    temp_path = default_storage.save(UPLOAD_TEMP_DIR / file_obj.name, file_obj)
    assert default_storage.size(temp_path) == file_obj.size
    download_url = default_storage.url(temp_path)

    # dict returned by the form on submission
    mime_type, sub_type = split_mime_type(file_obj.content_type)
    if mime_type == 'image':
        if sub_type == 'svg+xml':
            thumbnail_url = download_url
        else:
            thumbnail_url = thumbnail_image(default_storage, temp_path, image_height=image_height)
    else:
        thumbnail_url = file_icon_url(mime_type, sub_type)
    return {
        'upload_temp_name': signer.sign(temp_path),
        'content_type': f'{mime_type}/{sub_type}',
        'content_type_extra': file_obj.content_type_extra,
        'name': file_obj.name[:FILENAME_MAX_LENGTH],
        'download_url': download_url,
        'thumbnail_url': thumbnail_url,
        'size': file_obj.size,
    }
```
